# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Associazione IlClassico Musica e Arte APS
email: info@ilclassico.it
author: borsattoz

copyright: 'Copyright (cright) 2017-{currentYear} <a href="https://github.com/borsattoz">{author}</a>'

description: >- # this means to ignore newlines until "baseurl:"
  Scuola di Musica a Milano dal 1989

domain: borsattoz.github.io
url: "https://ilclassico.it"
baseurl: ""
logo: "/assets/images/logo.png"
favicon_root: "/assets/favicon"

yat:
  date_format: "%d %b %Y"

header_transparent: true

google_analytics: ""
enableDNT: "false"

sitemap: true

lang: "it"

theme_color: "#9eaec2"
brand_color: "#000"

night_mode: "off"

header_pages:
  - corsi.md
  - chi-siamo/insegnanti/index.md
  - chi-siamo/index.md
  - contatti/sede.md
  - contatti/index.md

defaults:
  home:
    heading: "Associazione IlClassico Musica e Arte APS"
    subheading: "Scuola di Musica a Milano dal 1989"
    banner:
      image: "/assets/images/banners/home.webp"
      opacity: 0.5
      background: "rgb(0, 0, 0)"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

theme: jekyll-theme-yat
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
